### ISSUE TITLE
MWE does not work

### ISSUE THREAD

**Issue by edmcman** [coin-or/rbfopt#12]
The MWE included in the README does not work:

    fuzz@UbuFuzz64:/data/uniqueness-scripts$ python mwe.py
    Traceback (most recent call last):
      File "mwe.py", line 7, in <module>
        np.array(['R', 'I', 'R']), obj_funct)
    TypeError: Can't instantiate abstract class RbfoptUserBlackBox with abstract methods evaluate_noisy, has_evaluate_noisy

**Comment by gnannicini** [comment]
Hi Edward,
thanks for bringing this up. It was a naming mismatch after refactoring.
Should be fixed on master now. Please check and let me know; I will make a bugfix release soon.

**Comment by edmcman** [comment]
Yup, that fixed it.  Thanks.
