### ISSUE TITLE
NameError: global name 'sys' is not defined

### ISSUE THREAD

**Issue by alessio-s** [coin-or/rbfopt#19]
It seems that in [rbfopt/rbfopt_refinement.py](https://github.com/coin-or/rbfopt/blob/master/src/rbfopt/rbfopt_refinement.py)

`import sys`

is necessary to correctly catch the exception in lines 136, 137.

**Comment by gnannicini** [comment]
I will fix it. Thanks a lot!

Giacomo

**Comment by jbustost** [comment]
Hi, guys: I tried to call on the sys module but still got this:

Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> sys.float_info.dig
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    sys.float_info.dig
NameError: name 'sys' is not defined
Could you help me out?

**Comment by whyDothItRun** [comment]
I'm having a similar issue myself: 

```
import time, subprocess, sys
from pynput.keyboard import Key, Controller

keyboard = Controller()

subprocess.call(['D:\Program Files\League of Legends\LeagueClient.exe'])




w = Sys.Process("Riot Client").WaitWindow("WindowClassName", "WindowCaption", 1, 500)
while not w.VisibleOnScreen:
  w = Sys.Process("Riot Client").WaitWindow("WindowClassName", "WindowCaption", 1, 500)

```

I'm trying to make a program that logs into the League of Legends client. I want it to detect if the window has opened before typing in the login details.

The error I get is 

> Traceback (most recent call last):
>   File "C:/Users/Daniel/PycharmProjects/leagueLogIn/Smurf.py", line 11, in <module>
>     w = Sys.Process("Riot Client").WaitWindow("WindowClassName", "WindowCaption", 1, 500)
> NameError: name 'Sys' is not defined

I'll keep googling and report back if I find a solution
