### ISSUE TITLE
 Error: "retrieving immutable Param value..." when calling .optimize()

### ISSUE THREAD

**Issue by Lskvk** [coin-or/rbfopt#20]
Hi,

there seems to be an Issue in rbfopt_degree_models.py. See the attachment for the error message
[errorMsg.txt](https://github.com/coin-or/rbfopt/files/2910496/errorMsg.txt)

In this particular case, I was able to fix this error by following:

https://groups.google.com/forum/#!topic/pyomo-forum/woioGPhpCFs

And changing line 869 in rbfopt_degree_models.py from:

                for i in model.K) + model.lambda_h[model.k])

to:

                for i in model.K) + model.lambda_h[model.k.value])

I'm using rbfopt v 4.0.3.

Best wishes,
Peter

**Comment by gnannicini** [comment]
Yes, apparently Pyomo changed the way to access parameter values.
Should be fixed in the latest commit and it seems to work even with older version.

https://github.com/coin-or/rbfopt/commit/96f629e90a9ce6ef79bfe50d638fb428793b23c8
