### ISSUE TITLE
Refactor RbfoptAlgorithm the way to make it possible to a library user drive the get_point-evaluate_point-update_model loop himself

### ISSUE THREAD

**Issue by KOLANICH** [coin-or/rbfopt#23]
I am writing a metaoptimizer (known as [UniOpt](https://gitlab.com/KOLANICH/UniOpt.py)) and there are some issues in this lib causing problems.

The most severe one is that the loop is not decoupled enough.
1 one cannot easily inject points. It can be worked around, but I don't think I should do it
2 the stuff prints all the initialization points, which can be thousands and millions. It is SLOW.

The solution can be is to allow a user to drive the loop himself,
```python
algo = RbfoptAlgorithm(...)
for i in range(countOfIters):
  point = algo.predict()
  result = f(point)
  algo[point] = result # updates the model
return algo.best
```

though this won't solve the multiprocessing issue (though for my case it is already broken because `pickle`, `cloudpickle` and `dill` refuse to serialize something in my program).

The solution is to allow the optimizer iterate the loop, but it contents is user-provided via a function too, and do it incrementally:

```python
def myFunc(algo_):
  point = algo_.predict()
  result = f(point)
  algo_[point] = result
algo = RbfoptAlgorithm(...)

for x, y in range(historicalPoints):
  algo[x] = y
algo.optimize(myFunc, count_of_iters)
... # inject points evaluated by other optimizers
algo.optimize(myFunc, count_of_iters)
```

Of course calling the funcs doesn;t mean anything should be printed.

**Comment by gnannicini** [comment]
Hi,
implementing what you suggest would not be trivial, as it would break many of the principles and assumptions used to design the algorithm and library. Basically, I don't really want users to inject whatever points they want. The points used by the algorithm must satisfy certain criteria and the numerics could break if these are not satisfied. 

Multiprocessing would be basically impossible in the setting that you suggest, I think.

Regarding output: you can disable output by setting a null output stream. This will stop any printing. In any case, if you are feeding millions of points to the algorithm, I don't think RBFOpt is the right choice. The iterations tend to get very slow if you have more than, say, 1000-2000 points. The algorithm is designed to be parsimonious and efficient at low iteration numbers, there are better methodologies out there if you plan to evaluate 10000 points anyways.

**Comment by KOLANICH** [comment]
Thank you for the info.

>Basically, I don't really want users to inject whatever points they want. The points used by the algorithm must satisfy certain criteria and the numerics could break if these are not satisfied.

Could you name them?

Do they apply to initialization points too? What are the negative consequences?

>Multiprocessing would be basically impossible in the setting that you suggest, I think.

Not sure in it. This loop is used in all black box optimizers in some form and this loop is inherently parallel if
* model itself decides when to stop the world and update itself
* order of injecting points doesn't matter much. I mean if we have a model derived from a suboptimal solution {(x, y)}_i, than we add p1=(x_1, y_1) and p2=(x_2, y_2), where x_1 and x_2 are predicted by this model, and then we the model updates itself resulting in {(x, y)}_(i+1),  x_3 doesn't depend on the order in which p1 and p2 were inserted

>Regarding output: you can disable output by setting a null output stream.

Thanks, will try.

>In any case, if you are feeding millions of points to the algorithm, I don't think RBFOpt is the right choice. The iterations tend to get very slow if you have more than, say, 1000-2000 points.

I have already noticed that :) I plan to measure time optimizer and evaluation takes and also gain, and basing on these metrics compute how many iterations to give to each optimizer in order to optimize the speed we go to the optima. The goal of metaoptimization is automatically take best of all the ensemble of optimizing algorithms.


>The algorithm is designed to be parsimonious and efficient at low iteration numbers

And it succeds in it! For Ackley-Rosenbrock hybrid function for 100 iterations MSRSM gives the best results, then Gutmann follows. Then other optimization libs.

>there are better methodologies out there if you plan to evaluate 10000 points anyways.

IMHO it should be decided automatically basing on fitness of optimizers to specific tast. BTW which ones do you feel I should add to UniOpt?
