### ISSUE TITLE
Constraint handling

### ISSUE THREAD

**Issue by adhe-k** [coin-or/rbfopt#31]
Hi,

I have a MINLP problem with constraints, and I want to solve my problem with rbfopt.
However, I can't find information about constraint handling in the documentation.
Does this library support constraint handling?

Best,
Adhe

**Comment by gnannicini** [comment]
Adhe,
it does not support constraints. If there are few constraints, you could try penalizing them in the objective function. This only works if a large part of the box domain is feasible, though.
There aren't many black-box optimization codes that support arbitrary constraints. If that's what you need, perhaps you could have a look at Nomad.

**Comment by adhe-k** [comment]
Yes, I need MINLP solver in python which handle black-box functions.
I have looked at Nomad, but can't find the python version.
Anyway, thanks for your answer.
