### ISSUE TITLE
Add optional arguments to UserBlackBox function

### ISSUE THREAD

**Issue by aaron1rcl** [coin-or/rbfopt#33]
The library is really useful, really appreciate the work.

It would be really helpful if it were possible to pass additional arguments to the black box function.
Correct me if I'm wrong, but it doesn't appear that this is currently possible.
I could add a kwargs parameter to the RbfoptUserBlackBox class init and propogate the values through.

**Comment by gnannicini** [comment]
You should be able to do what you're asking by using functools.partial:

https://docs.python.org/3/library/functools.html#functools.partial

Alternatively, you can define your own class with partially frozen arguments, e.g.,

`class FrozenObj:
  def __init__(self, unfrozen_obj, arg2):
    self.unfrozen_obj = unfrozen_obj
    self.arg2 = arg1

  def obj_func(self, x):
    return self.unfrozen_obj(x, arg2)`

Then you can instantiate FrozenObj and pass its obj_func method as the objective function. Using functools.partial yields the same result, with less code.

**Comment by aaron1rcl** [comment]
Thanks, sounds like a good solution. I will give that a go.
