### ISSUE TITLE
Unexpected error: "IndexError: index 160 is out of bounds for axis 0 with size 158"

### ISSUE THREAD

**Issue by cnelmortimer** [coin-or/rbfopt#43]
Dear RBFOpt team,

I am experiencing an unexpected problem with RBFOpt. After having prepared a fast or noisy function (expected to be 5 times faster than the accurate one), all my experiments seem to fail prematurely. Namely, I have launched 20 experiments and 4 of them have already failed with the following message:

Traceback (most recent call last):
  File "PySlim1.py", line 20, in <module>
    val, x, itercount, evalcount, fast_evalcount = alg.optimize()
  File "./venv/lib/python3.8/site-packages/rbfopt/rbfopt_algorithm.py", line 805, in optimize
    self.optimize_parallel(pause_after_iters)
  File "./venv/lib/python3.8/site-packages/rbfopt/rbfopt_algorithm.py", line 1384, in optimize_parallel
    if (not np.array_equal(self.node_pos[ind], next_p)):
IndexError: index 145 is out of bounds for axis 0 with size 145

For the rest, the last part varies as follows:
- IndexError: index 160 is out of bounds for axis 0 with size 158
- IndexError: index 153 is out of bounds for axis 0 with size 146
- IndexError: index 133 is out of bounds for axis 0 with size 109

And so on... Do you know the reason?

This is my code:

```
import rbfopt
import numpy as np
import NC_NormObjFunc
import NC_SlimNormObjFunc

def obj_funct(x):
        return (-1.0)*NC_NormObjFunc.NC_NormObjFunc(x)

def fast_funct(x):
        return np.array( [ (-1.0)*NC_SlimNormObjFunc.NC_SlimNormObjFunc(x), -0.10, 0.10 ] )

nvars = 13
bb = rbfopt.RbfoptUserBlackBox(nvars, np.array([0] * nvars), np.array([1] * nvars), np.array(['R'] * nvars), obj_funct, fast_funct)

settings = rbfopt.RbfoptSettings(num_cpus = 96, rand_seed = 3001, max_evaluations = 200, max_noisy_evaluations = 500, \
                        minlp_solver_path = './SOFTWARE/OPTIMIZERS/bonmin/bonmin', nlp_solver_path = './SOFTWARE/OPTIMIZERS/ipopt/ipopt')

alg = rbfopt.RbfoptAlgorithm(settings, bb)

val, x, itercount, evalcount, fast_evalcount = alg.optimize()
```

Finally, this is my former version that does not use a fast version of the objective function (and which has worked flawlessly):

```
import rbfopt
import numpy as np
import NC_NormObjFunc

def obj_funct(x):
        return (-1.0)*NC_NormObjFunc.NC_NormObjFunc(x)

nvars = 13
bb = rbfopt.RbfoptUserBlackBox(nvars, np.array([0] * nvars), np.array([1] * nvars), np.array(['R'] * nvars), obj_funct)

settings = rbfopt.RbfoptSettings(num_cpus = 96, rand_seed = 3001, max_evaluations = 300, \
                        minlp_solver_path = './SOFTWARE/OPTIMIZERS/bonmin/bonmin', nlp_solver_path = './SOFTWARE/OPTIMIZERS/ipopt/ipopt')

alg = rbfopt.RbfoptAlgorithm(settings, bb)

val, x, itercount, evalcount, fast_evalcount = alg.optimize()

```
What do you think the problem is? Is this a bug maybe or a mistake in my configuration?

Kind regards and thank you in advance.

**Comment by gnannicini** [comment]
At a first glance, your configuration seems correct. It is possible that
this is a bug. Do you experience the same problem if you run the algorithm
in serial mode?
Debugging the parallel opportunistic algorithm is more complicated because,
due to the timing of the various threads, it is sometimes difficult to
replicate behavior.

**Comment by cnelmortimer** [comment]
Dear @gnannicini 

Thank you very much for your interest and fast answer. 

I will launch the new configuration in serial mode right now and tell you what I get. It may take some days until I provide you with these results because my cost function takes 1 hour per run approximately.

Kind regards and thank you again

**Comment by gnannicini** [comment]
Ok, thank you. I will also try to have a look at the code for parallel
noisy evaluation and see if I spot something strange. (To make it
clear: there are tests that check this portion of the code, but as I
said, due to nondeterminism it is difficult to debug and it is very
well possible that the unit tests missed some potential bug.)

**Comment by cnelmortimer** [comment]
Dear @gnannicini ,

I have further information about the problem (mainly statistics). Namely, I launched 20 experiments with the slow and fast functions: 11/20 failed, and 9/20 finished. The latter seem OK. For instance, part of one of the successful outputs:

Summary: iters 380 evals 200 noisy_evals 209 cycles  62 opt_time 25680.74 tot_time 25680.74 obj~       -0.523766 gap 100.00
Val: -0.5237656785
X: 

[0.3038356189 0.6631799091 0.1689633477 0.0622767556 0.2985001215
 0.6408836672 0.1913555585 0.5582538902 0.2603603643 0.8866957041
 0.2669261029 0.077975326  0.236251292 ]


Itercount: 380
Evalcount: 200
Fast_evalcount: 209

The three serial ones that I launched are still running too.

Kind regards!

**Comment by gnannicini** [comment]
I found a bug that could have caused it. I updated the master branch; let me know if you have a chance to try it and see if it fixes it. I will prepare a new release.

The bug is caused by the algorithm trying to update the data structure of a noisy point that is currently being evaluated with the "accurate" objective function. This shouldn't happen, but if you have a lot of threads, it can happen. It should be fixed now, assuming that was the issue responsible for your crashes.

**Comment by cnelmortimer** [comment]
Dear @gnannicini ,

I am very happy for you to have found a bug. Congratulations! I hope that it was which caused my problems. We definitely use many threads: 96!

I want to try the fixed version and, of course, will tell you if my problems disappeared. **However**, I am not sure about how to update my copy of RBFOpt: It was installed through PIP, and I am not used to work with Python. How can I reflect your changes to test them?

Kind regards and thank you again!

**Comment by cnelmortimer** [comment]
Dear @gnannicini ,

Since you made a new release, I executed pip install --upgrade rbfopt to get the new version and repeated my experiments. This time, none failed, so it seems that the bug that you find was responsible for my problems. Accordingly, I will close this issue.

Thank you again for your help and for releasing RBFOpt.

Kind regards!
